### PR TITLE
Start finish time bug

### PR DESCRIPTION
**Pull request by enonnai**
Contents:
- user cannot add an end date that starts before the start date and gets notified by an error message
- Use flash notice for errors across the application
- display logic added to application view

### CODE REVIEW

**Comment by j311y** [comment]
The flash messages are working nicely. I noticed you can still add a start and finish date in the past.

**Review by BenNoonan1991 — APPROVED** [review]
:shipit:

**Comment by enonnai** [comment]
@jonathanelliot could you please tell us about steps to reproduce? I entered a start date 26th June and end date 25th June and it didn't let me, I got the flash errors.

**Review by j311y — APPROVED** [review]
:shipit:

**Pull request merged**
