### PR TITLE
Hide api

### PR DESCRIPTION
**Pull request by enonnai**
- Hide api key in test and development environments
- Remove footer as it overlaps the Submit button in Create Event Page, making 5 tests fail

### CODE REVIEW

**Comment by j311y** [comment]
Removed the footer and css completely.

**Review by j311y — APPROVED** [review]
nice :shipit:

**Review by BenNoonan1991 — APPROVED** [review]
:shipit:

**Review by axcochrane — APPROVED** [review]
:shipit:

**Pull request merged**
